name: Build Debug APK

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:

  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "V4A Dev (#${{github.run_number}})"
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
